const STATUS_IN_PROGRESS = { id: 1, name: 'В работе', color: 'yellow.400', icon: '🟨' }
const STATUS_DONE = { id: 1, name: 'Расчитан', color: 'uley_green.0', icon: '🟩' }
const STATUS_NEW = { id: 1, name: 'Новый', color: 'uley_orange.0', icon: '🟧' }

let ic = '🟥🟦🟪'

const STATUS_START = { id: 1, name: 'Старт', color: '#16b614', icon: '🟩' }
const STATUS_END = { id: 2, name: 'Стоп', color: '#f9c914', icon: '🟨' }
const STATUS_YES24 = { id: 3, name: '24', color: '#8b00ff', icon: '🟨' }
const STATUS_YES2 = { id: 4, name: '120', color: '#8b00ff', icon: '🟨' }
const STATUS_DRIVE = { id: 5, name: 'В пути', color: '#8b00ff', icon: '🟪' }
const STATUS_SPOT = { id: 6, name: 'На месте', color: '#065df1', icon: '🟦' }
const STATUS_LATE = { id: 7, name: 'Опоздание', color: '#ff0000', icon: '🟥' }

const onairStatuses3 = [
  {
    id: 1,
    specialist: 'Иванов Иван Иванович',
    start24: { value: '—', icon: '❌', status: 'none' },
    start120: { value: '08:08', icon: '✔️', status: 'done' },
    drive: { value: '08:08', icon: '✔', status: 'done' },
    spot: { value: '—', icon: '❌', status: 'none' },
    start: { value: '10:08', icon: '✔', status: 'late' },
    finish: { value: '—', icon: '❌', status: 'none' },
    comment: 'Тестовый Комментарий',
  },
  {
    id: 2,
    specialist: 'Петров Петр Петрович',
    start24: { value: '—', icon: '❌', status: 'none' },
    start120: { value: '08:01', icon: '✔️', status: 'done' },
    drive: { value: '08:25', icon: '✔️', status: 'done' },
    spot: { value: '—', icon: '❌', status: 'none' },
    start: { value: '—', icon: '❌', status: 'none' },
    finish: { value: '—', icon: '❌', status: 'none' },
    comment: 'Тестовый Комментарий',
  },
  {
    id: 3,

    specialist: 'Сидоров Сидор Сидорович',

    start24: { value: '—', icon: '❌', status: 'none' },
    start120: { value: '08:02', icon: '✔️', status: 'done' },
    drive: { value: '—', icon: '❌', status: 'none' },
    spot: { value: '—', icon: '❌', status: 'none' },
    start: { value: '—', icon: '❌', status: 'none' },
    finish: { value: '—', icon: '❌', status: 'none' },
    comment: 'Тестовый Комментарий',
  },
  {
    id: 4,

    specialist: 'Федоров Федор Федорович',

    start24: { value: '—', icon: '❌', status: 'none' },
    start120: { value: '08:03', icon: '✔️', status: 'done' },
    drive: { value: '—', icon: '❌', status: 'none' },
    spot: { value: '—', icon: '❌', status: 'none' },
    start: { value: '—', icon: '❌', status: 'none' },
    finish: { value: '—', icon: '❌', status: 'none' },
    comment: 'Тестовый Комментарий',
  },
  {
    id: 5,

    specialist: 'Яковлев Яков Яковлевич',

    start24: { value: '—', icon: '❌', status: 'none' },
    start120: { value: '08:05', icon: '✔️', status: 'done' },
    drive: { value: '—', icon: '❌', status: 'none' },
    spot: { value: '—', icon: '❌', status: 'none' },
    start: { value: '—', icon: '❌', status: 'none' },
    finish: { value: '—', icon: '❌', status: 'none' },
    comment: 'Тестовый Комментарий',
  },
]

const onairStatuses = [
  {
    id: 1,
    project_id: 1,
    specialist: 'Молчанов Дмитрий Улебович',
    start24: { value: '—', status: 'none' },
    start120: { value: '08:08', status: 'done' },
    drive: { value: '08:09', status: 'done' },
    spot: { value: '—', status: 'none' },
    start: { value: '10:08', status: 'late' },
    finish: { value: '—', status: 'none' },
    comment: 'Тестовый Комментарий',
  },
  {
    id: 2,
    project_id: 1,
    specialist: 'Тихонов Всеволод Альвианович',
    start24: { value: '—', status: 'none' },
    start120: { value: '08:01', status: 'done' },
    drive: { value: '08:25', status: 'done' },
    spot: { value: '—', status: 'none' },
    start: { value: '—', status: 'none' },
    finish: { value: '—', status: 'none' },
    comment: 'Тестовый Комментарий',
  },
  {
    id: 3,
    project_id: 1,
    specialist: 'Мухин Касьян Мартынович',
    start24: { value: '—', status: 'none' },
    start120: { value: '08:02', status: 'done' },
    drive: { value: '—', status: 'none' },
    spot: { value: '—', status: 'none' },
    start: { value: '—', status: 'none' },
    finish: { value: '—', status: 'none' },
    comment: 'Тестовый Комментарий',
  },
  {
    id: 4,
    project_id: 1,
    specialist: 'Громов Дональд Серапионович',
    start24: { value: '—', status: 'none' },
    start120: { value: '08:03', status: 'done' },
    drive: { value: '—', status: 'none' },
    spot: { value: '—', status: 'none' },
    start: { value: '—', status: 'none' },
    finish: { value: '—', status: 'none' },
    comment: 'Тестовый Комментарий',
  },
  {
    id: 5,
    project_id: 1,
    specialist: 'Лазарев Варлам Альвианович',
    start24: { value: '—', status: 'none' },
    start120: { value: '09:05', status: 'done' },
    drive: { value: '—', status: 'none' },
    spot: { value: '—', status: 'none' },
    start: { value: '—', status: 'none' },
    finish: { value: '—', status: 'none' },
    comment: 'Тестовый Комментарий',
  },
  {
    id: 6,
    project_id: 2,
    specialist: 'Кулаков Абрам Святославович',
    start24: { value: '—', status: 'none' },
    start120: { value: '09:06', status: 'done' },
    drive: { value: '09:07', status: 'done' },
    spot: { value: '—', status: 'none' },
    start: { value: '11:00', status: 'done' },
    finish: { value: '20:23', status: 'done' },
    comment: 'Тестовый Комментарий',
  },
  {
    id: 7,
    project_id: 2,
    specialist: 'Фролов Игнатий Романович',
    start24: { value: '—', status: 'none' },
    start120: { value: '09:06', status: 'done' },
    drive: { value: '09:07', status: 'done' },
    spot: { value: '—', status: 'none' },
    start: { value: '11:10', status: 'late' },
    finish: { value: '20:06', status: 'done' },
    comment: 'Тестовый Комментарий',
  },
  {
    id: 8,
    project_id: 2,
    specialist: 'Соловьёв Аркадий Степанович',
    start24: { value: '—', status: 'none' },
    start120: { value: '09:05', status: 'done' },
    drive: { value: '09:07', status: 'done' },
    spot: { value: '11:07', status: 'done' },
    start: { value: '11:08', status: 'late' },
    finish: { value: '20:07', status: 'done' },
    comment: 'Тестовый Комментарий',
  },
  {
    id: 9,
    project_id: 2,
    specialist: 'Щукин Никифор Валерьянович',
    start24: { value: '—', status: 'none' },
    start120: { value: '09:12', status: 'done' },
    drive: { value: '09:13', status: 'done' },
    spot: { value: '—', status: 'none' },
    start: { value: '10:58', status: 'done' },
    finish: { value: '20:36', status: 'done' },
    comment: 'Тестовый Комментарий',
  },
  {
    id: 10,
    project_id: 2,
    specialist: 'Ситников Альберт Дмитрьевич',
    start24: { value: '—', status: 'none' },
    start120: { value: '09:07', status: 'done' },
    drive: { value: '09:07', status: 'done' },
    spot: { value: '10:56', status: 'done' },
    start: { value: '10:56', status: 'done' },
    finish: { value: '20:07', status: 'done' },
    comment: 'Тестовый Комментарий',
  },
  {
    id: 11,
    project_id: 2,
    specialist: 'Исаев Владимир Ростиславович',
    start24: { value: '—', status: 'none' },
    start120: { value: '09:06', status: 'done' },
    drive: { value: '09:08', status: 'done' },
    spot: { value: '10:56', status: 'done' },
    start: { value: '10:56', status: 'done' },
    finish: { value: '20:37', status: 'done' },
    comment: 'Тестовый Комментарий',
  },
  {
    id: 12,
    project_id: 3,
    specialist: 'Ширяев Любомир Куприянович',
    start24: { value: '—', status: 'none' },
    start120: { value: '07:00', status: 'done' },
    drive: { value: '07:00', status: 'done' },
    spot: { value: '09:00', status: 'done' },
    start: { value: '09:01', status: 'late' },
    finish: { value: '19:37', status: 'done' },
    comment: 'Тестовый Комментарий',
  },
  {
    id: 13,
    project_id: 3,
    specialist: 'Кошелев Лавр Антонинович',
    start24: { value: '—', status: 'none' },
    start120: { value: '07:05', status: 'done' },
    drive: { value: '07:00', status: 'done' },
    spot: { value: '08:45', status: 'done' },
    start: { value: '08:55', status: 'done' },
    finish: { value: '19:26', status: 'done' },
    comment: 'Тестовый Комментарий',
  },
  {
    id: 14,
    project_id: 3,
    specialist: 'Константинов Вальтер Натанович',
    start24: { value: '—', status: 'none' },
    start120: { value: '07:04', status: 'done' },
    drive: { value: '07:05', status: 'done' },
    spot: { value: '08:37', status: 'done' },
    start: { value: '08:56', status: 'done' },
    finish: { value: '20:12', status: 'done' },
    comment: 'Тестовый Комментарий',
  },
  {
    id: 15,
    project_id: 3,
    specialist: 'Емельянов Мартин Михаилович',
    start24: { value: '—', status: 'none' },
    start120: { value: '07:15', status: 'done' },
    drive: { value: '07:26', status: 'done' },
    spot: { value: '09:10', status: 'done' },
    start: { value: '09:10', status: 'late' },
    finish: { value: '19:45', status: 'done' },
    comment: 'Тестовый Комментарий',
  },
  {
    id: 16,
    project_id: 4,
    specialist: 'Тетерин Варлаам Донатович',
    start24: { value: '—', status: 'none' },
    start120: { value: '08:05', status: 'done' },
    drive: { value: '08:25', status: 'done' },
    spot: { value: '10:00', status: 'done' },
    start: { value: '10:00', status: 'done' },
    finish: { value: '—', status: 'none' },
    comment: 'Тестовый Комментарий',
  },
  {
    id: 17,
    project_id: 4,
    specialist: 'Жуков Рубен Германнович',
    start24: { value: '—', status: 'none' },
    start120: { value: '08:05', status: 'done' },
    drive: { value: '08:36', status: 'done' },
    spot: { value: '09:52', status: 'done' },
    start: { value: '09:56', status: 'done' },
    finish: { value: '—', status: 'none' },
    comment: 'Тестовый Комментарий',
  },
  {
    id: 18,
    project_id: 4,
    specialist: 'Быков Вениамин Якунович',
    start24: { value: '—', status: 'none' },
    start120: { value: '08:05', status: 'done' },
    drive: { value: '08:05', status: 'done' },
    spot: { value: '09:58', status: 'done' },
    start: { value: '09:59', status: 'done' },
    finish: { value: '—', status: 'none' },
    comment: 'Тестовый Комментарий',
  },
  {
    id: 19,
    project_id: 4,
    specialist: 'Зимин Витольд Федотович',
    start24: { value: '—', status: 'none' },
    start120: { value: '08:25', status: 'done' },
    drive: { value: '08:45', status: 'done' },
    spot: { value: '09:36', status: 'done' },
    start: { value: '10:00', status: 'done' },
    finish: { value: '—', status: 'none' },
    comment: 'Тестовый Комментарий',
  },
  {
    id: 20,
    project_id: 4,
    specialist: 'Корнилов Игорь Созонович',
    start24: { value: '—', status: 'none' },
    start120: { value: '08:05', status: 'done' },
    drive: { value: '08:35', status: 'done' },
    spot: { value: '10:00', status: 'done' },
    start: { value: '10:00', status: 'done' },
    finish: { value: '—', status: 'none' },
    comment: 'Тестовый Комментарий',
  },
  {
    id: 21,
    project_id: 4,
    specialist: 'Аксёнов Рубен Филатович',
    start24: { value: '—', status: 'none' },
    start120: { value: '08:05', status: 'done' },
    drive: { value: '08:45', status: 'done' },
    spot: { value: '10:05', status: 'done' },
    start: { value: '10:05', status: 'late' },
    finish: { value: '—', status: 'none' },
    comment: 'Тестовый Комментарий',
  },
  {
    id: 22,
    project_id: 4,
    specialist: 'Беляков Гаянэ Донатович',
    start24: { value: '—', status: 'none' },
    start120: { value: '08:05', status: 'done' },
    drive: { value: '08:15', status: 'done' },
    spot: { value: '10:06', status: 'done' },
    start: { value: '10:06', status: 'late' },
    finish: { value: '—', status: 'none' },
    comment: 'Тестовый Комментарий',
  },
]

export default onairStatuses
