const STATUS_IN_PROGRESS = { id: 1, name: 'В работе', color: 'yellow.400', icon: '🟨' }
const STATUS_DONE = { id: 1, name: 'Расчитан', color: 'uley_green.0', icon: '🟩' }
const STATUS_NEW = { id: 1, name: 'Новый', color: 'uley_orange.0', icon: '🟧' }

let ic = '🟥🟦🟪'

const STATUS_START = { id: 1, name: 'Старт', color: '#16b614', icon: '🟩' }
const STATUS_END = { id: 2, name: 'Стоп', color: '#f9c914', icon: '🟨' }
const STATUS_YES24 = { id: 3, name: '24', color: '#8b00ff', icon: '🟨' }
const STATUS_YES2 = { id: 4, name: '120', color: '#8b00ff', icon: '🟨' }
const STATUS_DRIVE = { id: 5, name: 'В пути', color: '#8b00ff', icon: '🟪' }
const STATUS_SPOT = { id: 6, name: 'На месте', color: '#065df1', icon: '🟦' }
const STATUS_LATE = { id: 7, name: 'Опоздание', color: '#ff0000', icon: '🟥' }

const onairStatuses3 = [
  {
    id: 1,
    specialist: 'Иванов Иван Иванович',
    start24: { value: '—', icon: '❌', status: 'none' },
    start120: { value: '08:08', icon: '✔️', status: 'done' },
    drive: { value: '08:08', icon: '✔', status: 'done' },
    spot: { value: '—', icon: '❌', status: 'none' },
    start: { value: '10:08', icon: '✔', status: 'late' },
    finish: { value: '—', icon: '❌', status: 'none' },
    comment: 'Тестовый Комментарий',
  },
  {
    id: 2,
    specialist: 'Петров Петр Петрович',
    start24: { value: '—', icon: '❌', status: 'none' },
    start120: { value: '08:01', icon: '✔️', status: 'done' },
    drive: { value: '08:25', icon: '✔️', status: 'done' },
    spot: { value: '—', icon: '❌', status: 'none' },
    start: { value: '—', icon: '❌', status: 'none' },
    finish: { value: '—', icon: '❌', status: 'none' },
    comment: 'Тестовый Комментарий',
  },
  {
    id: 3,

    specialist: 'Сидоров Сидор Сидорович',

    start24: { value: '—', icon: '❌', status: 'none' },
    start120: { value: '08:02', icon: '✔️', status: 'done' },
    drive: { value: '—', icon: '❌', status: 'none' },
    spot: { value: '—', icon: '❌', status: 'none' },
    start: { value: '—', icon: '❌', status: 'none' },
    finish: { value: '—', icon: '❌', status: 'none' },
    comment: 'Тестовый Комментарий',
  },
  {
    id: 4,

    specialist: 'Федоров Федор Федорович',

    start24: { value: '—', icon: '❌', status: 'none' },
    start120: { value: '08:03', icon: '✔️', status: 'done' },
    drive: { value: '—', icon: '❌', status: 'none' },
    spot: { value: '—', icon: '❌', status: 'none' },
    start: { value: '—', icon: '❌', status: 'none' },
    finish: { value: '—', icon: '❌', status: 'none' },
    comment: 'Тестовый Комментарий',
  },
  {
    id: 5,

    specialist: 'Яковлев Яков Яковлевич',

    start24: { value: '—', icon: '❌', status: 'none' },
    start120: { value: '08:05', icon: '✔️', status: 'done' },
    drive: { value: '—', icon: '❌', status: 'none' },
    spot: { value: '—', icon: '❌', status: 'none' },
    start: { value: '—', icon: '❌', status: 'none' },
    finish: { value: '—', icon: '❌', status: 'none' },
    comment: 'Тестовый Комментарий',
  },
]

const onairStatuses = [
  {
    id: 1,
    project_id: 1,
    specialist: 'Молчанов Дмитрий Улебович',
    start24: { value: '—', status: 'none' },
    start120: { value: '07:01', status: 'done' },
    drive: { value: '07:32', status: 'done' },
    spot: { value: '08:37', status: 'done' },
    start: { value: '09:01', status: 'late' },
    finish: { value: '—', status: 'none' },
    comment: 'Тестовый Комментарий',
  },
  {
    id: 2,
    project_id: 1,
    specialist: 'Тихонов Всеволод Альвианович',
    start24: { value: '—', status: 'none' },
    start120: { value: '07:03', status: 'done' },
    drive: { value: '07:15', status: 'done' },
    spot: { value: '08:55', status: 'done' },
    start: { value: '09:00', status: 'done' },
    finish: { value: '—', status: 'none' },
    comment: 'Тестовый Комментарий',
  },
  {
    id: 3,
    project_id: 1,
    specialist: 'Мухин Касьян Мартынович',
    start24: { value: '—', status: 'none' },
    start120: { value: '07:15', status: 'done' },
    drive: { value: '08:12', status: 'none' },
    spot: { value: '08:57', status: 'none' },
    start: { value: '09:05', status: 'late' },
    finish: { value: '—', status: 'none' },
    comment: 'Тестовый Комментарий',
  },
  {
    id: 4,
    project_id: 1,
    specialist: 'Громов Дональд Серапионович',
    start24: { value: '—', status: 'none' },
    start120: { value: '07:00', status: 'done' },
    drive: { value: '08:46', status: 'done' },
    spot: { value: '08:49', status: 'done' },
    start: { value: '08:58', status: 'done' },
    finish: { value: '—', status: 'none' },
    comment: 'Тестовый Комментарий',
  },
  {
    id: 5,
    project_id: 1,
    specialist: 'Лазарев Варлам Альвианович',
    start24: { value: '—', status: 'none' },
    start120: { value: '07:40', status: 'done' },
    drive: { value: '08:33', status: 'done' },
    spot: { value: '09:15', status: 'done' },
    start: { value: '09:32', status: 'done' },
    finish: { value: '—', status: 'none' },
    comment: 'Тестовый Комментарий',
  },
  {
    id: 6,
    project_id: 2,
    specialist: 'Кулаков Абрам Святославович',
    start24: { value: '—', status: 'none' },
    start120: { value: '08:02', status: 'done' },
    drive: { value: '08:05', status: 'done' },
    spot: { value: '09:35', status: 'done' },
    start: { value: '10:00', status: 'done' },
    finish: { value: '18:13', status: 'done' },
    comment: 'Тестовый Комментарий',
  },
  {
    id: 7,
    project_id: 2,
    specialist: 'Фролов Игнатий Романович',
    start24: { value: '—', status: 'none' },
    start120: { value: '08:17', status: 'done' },
    drive: { value: '09:04', status: 'done' },
    spot: { value: '09:55', status: 'done' },
    start: { value: '10:01', status: 'late' },
    finish: { value: '18:00', status: 'done' },
    comment: 'Тестовый Комментарий',
  },
  {
    id: 8,
    project_id: 2,
    specialist: 'Соловьёв Аркадий Степанович',
    start24: { value: '—', status: 'none' },
    start120: { value: '08:05', status: 'done' },
    drive: { value: '08:25', status: 'done' },
    spot: { value: '09:47', status: 'done' },
    start: { value: '10:00', status: 'done' },
    finish: { value: '18:15', status: 'done' },
    comment: 'Тестовый Комментарий',
  },
  {
    id: 9,
    project_id: 2,
    specialist: 'Щукин Никифор Валерьянович',
    start24: { value: '—', status: 'none' },
    start120: { value: '08:37', status: 'done' },
    drive: { value: '09:35', status: 'done' },
    spot: { value: '10:10', status: 'done' },
    start: { value: '10:15', status: 'done' },
    finish: { value: '18:49', status: 'done' },
    comment: 'Тестовый Комментарий',
  },
  {
    id: 10,
    project_id: 2,
    specialist: 'Ситников Альберт Дмитрьевич',
    start24: { value: '—', status: 'none' },
    start120: { value: '—', status: 'none' },
    drive: { value: '08:33', status: 'done' },
    spot: { value: '09:57', status: 'done' },
    start: { value: '10:03', status: 'late' },
    finish: { value: '18:00', status: 'done' },
    comment: 'Тестовый Комментарий',
  },
  {
    id: 11,
    project_id: 2,
    specialist: 'Исаев Владимир Ростиславович',
    start24: { value: '—', status: 'none' },
    start120: { value: '08:13', status: 'done' },
    drive: { value: '09:15', status: 'done' },
    spot: { value: '10:00', status: 'done' },
    start: { value: '10:12', status: 'late' },
    finish: { value: '18:45', status: 'done' },
    comment: 'Тестовый Комментарий',
  },
  {
    id: 12,
    project_id: 3,
    specialist: 'Ширяев Любомир Куприянович',
    start24: { value: '—', status: 'none' },
    start120: { value: '08:33', status: 'done' },
    drive: { value: '08:50', status: 'done' },
    spot: { value: '09:50', status: 'done' },
    start: { value: '10:25', status: 'done' },
    finish: { value: '22:02', status: 'done' },
    comment: 'Тестовый Комментарий',
  },
  {
    id: 13,
    project_id: 3,
    specialist: 'Кошелев Лавр Антонинович',
    start24: { value: '—', status: 'none' },
    start120: { value: '08:45', status: 'done' },
    drive: { value: '09:00', status: 'done' },
    spot: { value: '10:15', status: 'done' },
    start: { value: '10:31', status: 'late' },
    finish: { value: '21:55', status: 'done' },
    comment: 'Тестовый Комментарий',
  },
  {
    id: 14,
    project_id: 3,
    specialist: 'Константинов Вальтер Натанович',
    start24: { value: '—', status: 'none' },
    start120: { value: '08:33', status: 'done' },
    drive: { value: '—', status: 'none' },
    spot: { value: '—', status: 'none' },
    start: { value: '—', status: 'none' },
    finish: { value: '—', status: 'none' },
    comment: 'Тестовый Комментарий',
  },
  {
    id: 15,
    project_id: 3,
    specialist: 'Емельянов Мартин Михаилович',
    start24: { value: '—', status: 'none' },
    start120: { value: '08:30', status: 'done' },
    drive: { value: '08:49', status: 'done' },
    spot: { value: '10:25', status: 'done' },
    start: { value: '10:36', status: 'late' },
    finish: { value: '22:05', status: 'done' },
    comment: 'Тестовый Комментарий',
  },
  {
    id: 16,
    project_id: 4,
    specialist: 'Тетерин Варлаам Донатович',
    start24: { value: '—', status: 'none' },
    start120: { value: '12:05', status: 'done' },
    drive: { value: '13:00', status: 'done' },
    spot: { value: '13:45', status: 'done' },
    start: { value: '14:00', status: 'done' },
    finish: { value: '20:00', status: 'done' },
    comment: 'Тестовый Комментарий',
  },
  {
    id: 17,
    project_id: 4,
    specialist: 'Жуков Рубен Германнович',
    start24: { value: '—', status: 'none' },
    start120: { value: '12:00', status: 'done' },
    drive: { value: '12:30', status: 'done' },
    spot: { value: '13:15', status: 'done' },
    start: { value: '14:02', status: 'late' },
    finish: { value: '20:03', status: 'done' },
    comment: 'Тестовый Комментарий',
  },
  {
    id: 18,
    project_id: 4,
    specialist: 'Быков Вениамин Якунович',
    start24: { value: '—', status: 'none' },
    start120: { value: '12:13', status: 'done' },
    drive: { value: '15:55', status: 'done' },
    spot: { value: '15:58', status: 'done' },
    start: { value: '14:15', status: 'done' },
    finish: { value: '20:15', status: 'done' },
    comment: 'Тестовый Комментарий',
  },
  {
    id: 19,
    project_id: 4,
    specialist: 'Зимин Витольд Федотович',
    start24: { value: '—', status: 'none' },
    start120: { value: '12:00', status: 'done' },
    drive: { value: '12:40', status: 'done' },
    spot: { value: '—', status: 'none' },
    start: { value: '—', status: 'none' },
    finish: { value: '—', status: 'none' },
    comment: 'Тестовый Комментарий',
  },
  {
    id: 20,
    project_id: 4,
    specialist: 'Корнилов Игорь Созонович',
    start24: { value: '—', status: 'none' },
    start120: { value: '12:00', status: 'done' },
    drive: { value: '12:37', status: 'done' },
    spot: { value: '13:55', status: 'done' },
    start: { value: '14:00', status: 'done' },
    finish: { value: '20:02', status: 'none' },
    comment: 'Тестовый Комментарий',
  },
  {
    id: 21,
    project_id: 4,
    specialist: 'Аксёнов Рубен Филатович',
    start24: { value: '—', status: 'none' },
    start120: { value: '12:12', status: 'done' },
    drive: { value: '12:20', status: 'done' },
    spot: { value: '13:00', status: 'done' },
    start: { value: '13:55', status: 'done' },
    finish: { value: '20:05', status: 'done' },
    comment: 'Тестовый Комментарий',
  },
  {
    id: 22,
    project_id: 4,
    specialist: 'Беляков Гаянэ Донатович',
    start24: { value: '—', status: 'none' },
    start120: { value: '12:45', status: 'done' },
    drive: { value: '13:25', status: 'done' },
    spot: { value: '14:15', status: 'done' },
    start: { value: '14:20', status: 'late' },
    finish: { value: '20:10', status: 'none' },
    comment: 'Тестовый Комментарий',
  },
]

export default onairStatuses
